name: ChatBeautifier
version: '${version}'
main: dev.eymen.ChatBeautifier
api-version: 1.18
authors: [Deliable]
description: Beautify your chat
website: eymen.dev
softdepend: [ItemsAdder, Oraxen, PlaceholderAPI, MiniPlaceholders]