name: SmallCaps
version: '${project.version}'
main: dev.eymen.smallcaps.SmallCaps
api-version: 1.13
authors: [Deliable]
description: Convert normal sentences to small caps sentences
website: eymen.dev
softdepend: [PlaceholderAPI]
commands:
  smallcaps:
    description: Convert normal sentences to small caps sentences
    usage: /smallcaps <sentence>
    aliases: [convertsmallcaps, smallcapsconvert, smallcapsconverter]