name: SmallCaps
version: '1.0.0-STABLE'
main: dev.eymen.smallcaps.SmallCaps
api-version: 1.8
authors: [Deliable]
description: Convert normal sentences to small caps sentences
website: eymen.dev
softdepend: [PlaceholderAPI]
commands:
  smallcaps:
    description: Convert normal sentences to small caps sentences
    usage: /smallcaps <sentence>
    aliases: [convertsmallcaps, smallcapsconvert, smallcapsconverter]